//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoPaso1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contextTienda : DbContext
    {
        public contextTienda()
            : base("name=contextTienda")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<dirEntrega> dirEntrega { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<orden> orden { get; set; }
        public virtual DbSet<orden_producto> orden_producto { get; set; }
        public virtual DbSet<Paqueteria> Paqueteria { get; set; }
        public virtual DbSet<producto> producto { get; set; }
    }
}
