//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoPaso1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paqueteria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paqueteria()
        {
            this.orden = new HashSet<orden>();
        }
    
        public int IdPaqueteria { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string Tel { get; set; }
        public string Web { get; set; }
        public string Direccion { get; set; }
        public string Contacto { get; set; }
        public string telContacto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
